FROM plantuml/plantuml-server:tomcat

ARG ROOT_PASS=
ARG USERNAME=

RUN for arg in ROOT_PASS USERNAME; \
  do \
  [ ! -z "${arg}" ] || { echo "ARG \"$arg\" needs to be set"; exit 1; } \
  done;

SHELL ["/bin/bash", "-c"]
ENV SHELL /bin/bash

RUN apt update && apt upgrade -y && apt install \
  git \
  curl \
  vim \
  -y 

RUN echo "root:$ROOT_PASS" | chpasswd
RUN useradd -m $USERNAME
USER $USERNAME

# Gists
ADD --chown=$USERNAME:$GROUP \
  https://gist.githubusercontent.com/utkusarioglu/2d4be44dc7707afccd540ad99ba385e6/raw/create-env-example.sh \
  /scripts/create-env-example.sh

ADD --chown=$USERNAME:$GROUP \
  https://gist.githubusercontent.com/utkusarioglu/3523b00578807d63b05399fe57a4b2a7/raw/.bashrc \
  /home/$USERNAME/.bashrc

ADD --chown=$USERNAME:$GROUP \
  https://gist.githubusercontent.com/utkusarioglu/d5c216c744460c45bf6260d0de4131b4/raw/.inputrc \
  /home/$USERNAME/.inputrc

RUN chmod +x \
  /scripts/create-env-example.sh \
  /home/$USERNAME/.bashrc \
  /home/$USERNAME/.inputrc
